[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "secret_of_mana"
client_id = "secret_client_id"
client_secret = "secret_client_secret"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
